### ISSUE TITLE
不能切换到里站

### ISSUE THREAD

**Issue by Tenkawa-tawawa** [tonquer/ehentai-qt#37]
### 操作系统（如MacOS 10.15）
>
win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
Homeplus Digital Co., Ltd.

### 问题描述（简要描述发生的问题）
>
之前能切换到里站，但现在不行。

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
点切换表里会显示解析出错了

### 日志提交（问题截图或者日志，日志在logs目录）
>
2022-11-09 02:02:04,774 - start.py[line:67] - WARNING: init scene ratio: 1.25
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
QLayout: Attempting to add QLayout "" to QWidget "LineEditHelp", which already has a layout
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
QLayout: Attempting to add QLayout "" to QWidget "LineEditHelp", which already has a layout
PySide2.QtCore.QSize(1536, 864) PySide2.QtCore.QSize(1152, 648)
[0 AMD Radeon(TM) Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[1]
[0 AMD Radeon(TM) Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon(TM) Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon(TM) Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
[1 NVIDIA GeForce RTX 3060 Laptop GPU]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[1 NVIDIA GeForce RTX 3060 Laptop GPU]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 NVIDIA GeForce RTX 3060 Laptop GPU]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 NVIDIA GeForce RTX 3060 Laptop GPU]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
2022-11-09 02:02:09,282 - main_view.py[line:135] - WARNING: Waifu2x init: 0 encode: 0 version:1.1.1 code:0 cpuNum:0
2022-11-09 02:02:09,702 - login_proxy.py[line:577] - WARNING: Serving HTTP Proxy on 127.0.0.1 port 8367 ...
2022-11-09 02:02:12,826 - login_view.py[line:185] - WARNING: login success, {'st': 1001, 'userId': '6843527', 'userName': 'l0909709257'}, cookie
2022-11-09 02:02:17,517 - user_handler.py[line:168] - ERROR: 'NoneType' object has no attribute 'tr'
Traceback (most recent call last):
  File "server\user_handler.py", line 159, in __call__
  File "tools\tool.py", line 309, in ParseBookIndex
AttributeError: 'NoneType' object has no attribute 'tr'

**Comment by Tenkawa-tawawa** [comment]
> 你能用网页访问吗

可以

**Comment by tonquer** [comment]
里站布局似乎变了，需要修改下 才可以

**Comment by fjf010223** [comment]
+1希望尽快修复

**Comment by tonquer** [comment]
v1.0.8已解决该问题

**Comment by Tenkawa-tawawa** [comment]
> v1.0.8已解决该问题

發現用Cookie登陸的話，沒填igneous是進不了里站的，感謝大大修復(*´∀`)~♥

**Comment by tonquer** [comment]
> > v1.0.8已解决该问题
> 
> 發現用Cookie登陸的話，沒填igneous是進不了里站的，感謝大大修復(*´∀`)~♥

没填的话，需要该账号可访问里站，并且用欧美ip访问才可获取到igneous
