### ISSUE TITLE
关闭界面时错误弹窗

### ISSUE THREAD

**Issue by Kano-I** [tonquer/ehentai-qt#44]
### 操作系统（如MacOS 10.15）
> Windows10_x64

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> Wifi 电信

### 问题描述（简要描述发生的问题）
> 以快捷方式启动后，每次关闭界面时都会弹出错误 ERROR框。使用原文件启动不会出现这一问题

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 使用快捷方式启动，关闭窗口就会出现

### 日志提交（问题截图或者日志，日志在logs目录）
> 
```
Traceback (most recent call last):
  File "start.py", line 94, in <module>
  File "view\main\main_view.py", line 383, in Stop
  File "tools\login_proxy.py", line 590, in Stop
AttributeError: 'NoneType' object has no attribute 'shutdown'
```
<img height="300" width="400" src='https://i.postimg.cc/hg4LwdQs/2022-12-10-09-38-44-653-a85e5ddee929e54942a3acc75841b5d7-e7d6724f.png?dl=1'></img>
<img height="300" width="400" src='https://i.postimg.cc/Cw0kGn0b/2022-12-10-09-43-36-649-8d8bc2d04153442b50357bc1bb845f2b-81a5f8db.png?dl=1'></img>

**Comment by Kano-I** [comment]
他正常工作了，纳闷🤣
