### ISSUE TITLE
进入程序，登录账户后报错

### ISSUE THREAD

**Issue by jackeywcy** [tonquer/ehentai-qt#47]
### 操作系统（如Win10 专业版 22H2）
>
### 网络环境（上海移动）
电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
> 进入程序后，登录账户后报错
Traceback (most recent call last):
  File "component\list\comic_list_widget.py", line 176, in LoadingPicture
  File "task\qt_task.py", line 103, in AddDownloadTask
  File "tools\qt_domain.py", line 70, in AddDownloadTask
AttributeError: 'str' object has no attribute 'cache_dns'

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 关闭程序，再次进入、登录账号，切换至exhentai后同样出错

### 日志提交（问题截图或者日志，日志在logs目录）
>
![image](https://user-images.githubusercontent.com/20952447/209932765-2bb4a901-f134-4aee-a3ad-525fd88a10bc.png)

**Comment by tonquer** [comment]
大概是设置中开启图片Doh引起的，可以暂时关闭，下版本修复
