### ISSUE TITLE
启用图片doh后报错

### ISSUE THREAD

**Issue by zuoling2447** [tonquer/ehentai-qt#49]
### 操作系统（如MacOS 10.15）
>Windows 11 25276.1000

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动宽带

### 问题描述（简要描述发生的问题）
>启用图片doh后报错
Traceback (most recent call last):
  File "component\list\comic_list_widget.py", line 176, in LoadingPicture
  File "task\qt_task.py", line 103, in AddDownloadTask
  File "tools\qt_domain.py", line 70, in AddDownloadTask
AttributeError: 'str' object has no attribute 'cache_dns'

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>启用图片doh后就会一直报错弹窗，关闭弹窗后软件自动关闭

### 日志提交（问题截图或者日志，日志在logs目录）
>
[20230114.log](https://github.com/tonquer/ehentai-qt/files/10416996/20230114.log)

**Comment by tonquer** [comment]
请更新v1.1.0版本
