### ISSUE TITLE
打开后出现Error Cache DNS

### ISSUE THREAD

**Issue by jackeywcy** [tonquer/ehentai-qt#56]
### 操作系统（如MacOS 10.15）
> 版本	Windows 10 专业版
版本号	22H2
安装日期	‎2022/‎11/‎14
操作系统内部版本	19045.2604
体验	Windows Feature Experience Pack 120.2212.4190.0

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 移动宽带

### 问题描述（简要描述发生的问题）
> 打开start.exe (debug) 输入账号并且登录后出现error 目录无中文
Traceback (most recent call last):
  File "component\list\comic_list_widget.py", line 176, in LoadingPicture
  File "task\qt_task.py", line 103, in AddDownloadTask
  File "tools\qt_domain.py", line 70, in AddDownloadTask
AttributeError: 'str' object has no attribute 'cache_dns'

![image](https://user-images.githubusercontent.com/20952447/221359880-dd42bc4e-c3c4-4565-a311-84eed2a353a7.png)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 打开start.exe 输入账号并且登录后稳定复现 安装目录无中文

### 日志提交（问题截图或者日志，日志在logs目录）
>
[20230225.log](https://github.com/tonquer/ehentai-qt/files/10
[20230225.log](https://github.com/tonquer/ehentai-qt/files/10831288/20230225.log)
831287/20230225.log)

**Comment by tonquer** [comment]
请更新v1.1.0版本
