### ISSUE TITLE
Mac 无法登录

### ISSUE THREAD

**Issue by linonetwo** [tonquer/ehentai-qt#58]
### 操作系统（如MacOS 10.15）
> MacOS

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 已翻墙

### 问题描述（简要描述发生的问题）
>

```
Traceback (most recent call last):
  File "view/user/login_view.py", line 65, in _ClickButton
  File "view/user/login_widget.py", line 43, in ClickButton
  File "view/user/login_widget.py", line 50, in Login
  File "qt_owner.py", line 45, in ShowError
  File "component/label/msg_label.py", line 137, in ShowErrorEx
  File "component/label/msg_label.py", line 33, in setText
TypeError: 'PySide6.QtWidgets.QLabel.setText' called with wrong argument types:
  PySide6.QtWidgets.QLabel.setText(int)
Supported signatures:
  PySide6.QtWidgets.QLabel.setText(str)
```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

https://user-images.githubusercontent.com/3746270/222875780-6d8042ba-f1b1-4df6-853a-c21d5602eec0.mov

### 日志提交（问题截图或者日志，日志在logs目录）
>

**Comment by tonquer** [comment]
现在应该是关闭那个错误弹框 就可以了
