### ISSUE TITLE
不断报错显示“连接被重置”

### ISSUE THREAD

**Issue by Sheng-P** [tonquer/ehentai-qt#59]
### 操作系统（如MacOS 10.15）
>MacOS 13.21

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>阿联酋Etisalat

### 问题描述（简要描述发生的问题）
>从首页点进作品时无法加载，弹出提示框显示“连接被重置”

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>打开程序后，首页报错，显示连接被重置，刷新后出现作品流，点进作品，无法加载，弹出提示框连接被重置

### 日志提交（问题截图或者日志，日志在logs目录）
>
2023-03-11 00:40:17,412 - start.py[line:68] - WARNING: init scene ratio: 2.0
2023-03-11 00:40:28,860 - main_view.py[line:140] - WARNING: Waifu2x init:0, encode:0, version:1.1.4, code:0, cpuNum:0/4, gpuNum:1, gpuList:['Intel(R) UHD Graphics 617']
2023-03-11 00:40:29,325 - login_proxy.py[line:577] - WARNING: Serving HTTP Proxy on 127.0.0.1 port 55124 ...
2023-03-11 00:40:41,957 - server.py[line:188] - WARNING: https://178.162.147.246 TooManyRedirects('Exceeded 30 redirects.')
2023-03-11 00:40:42,692 - server.py[line:188] - WARNING: https://178.162.139.18 TooManyRedirects('Exceeded 30 redirects.')
2023-03-11 00:40:42,994 - server.py[line:188] - WARNING: https://37.48.89.16 TooManyRedirects('Exceeded 30 redirects.')
2023-03-11 00:40:43,689 - server.py[line:188] - WARNING: https://81.171.10.55 TooManyRedirects('Exceeded 30 redirects.')
2023-03-11 00:44:18,988 - login_proxy.py[line:579] - WARNING: Serving end...
2023-03-11 00:50:59,879 - start.py[line:83] - WARNING: init scene ratio: 2.0
2023-03-11 00:51:03,514 - main_view.py[line:140] - WARNING: Waifu2x init:0, encode:0, version:1.1.6, code:0, cpuNum:0/4, gpuNum:1, gpuList:['Intel(R) UHD Graphics 617']
2023-03-11 00:51:04,659 - start.py[line:103] - ERROR: Traceback (most recent call last):
  File "view/user/login_view.py", line 50, in _AutoLogin
  File "view/user/login_widget.py", line 43, in ClickButton
  File "view/user/login_widget.py", line 50, in Login
  File "qt_owner.py", line 45, in ShowError
  File "component/label/msg_label.py", line 137, in ShowErrorEx
  File "component/label/msg_label.py", line 33, in setText
TypeError: 'PySide6.QtWidgets.QLabel.setText' called with wrong argument types:
  PySide6.QtWidgets.QLabel.setText(int)
Supported signatures:
  PySide6.QtWidgets.QLabel.setText(str)
NoneType: None
2023-03-11 00:51:08,216 - start.py[line:83] - WARNING: init scene ratio: 2.0
2023-03-11 00:51:11,089 - main_view.py[line:140] - WARNING: Waifu2x init:0, encode:0, version:1.1.6, code:0, cpuNum:0/4, gpuNum:1, gpuList:['Intel(R) UHD Graphics 617']
2023-03-11 00:51:12,172 - start.py[line:103] - ERROR: Traceback (most recent call last):
  File "view/user/login_view.py", line 50, in _AutoLogin
  File "view/user/login_widget.py", line 43, in ClickButton
  File "view/user/login_widget.py", line 50, in Login
  File "qt_owner.py", line 45, in ShowError
  File "component/label/msg_label.py", line 137, in ShowErrorEx
  File "component/label/msg_label.py", line 33, in setText
TypeError: 'PySide6.QtWidgets.QLabel.setText' called with wrong argument types:
  PySide6.QtWidgets.QLabel.setText(int)
Supported signatures:
  PySide6.QtWidgets.QLabel.setText(str)
NoneType: None
2023-03-11 00:52:10,931 - server.py[line:210] - WARNING: https://178.175.129.252/?inline_set=dm_l ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
2023-03-11 00:53:58,959 - server.py[line:210] - WARNING: https://104.20.134.21/g/2489605/952d0e6848/?hc=1&nw=always&inline_set=ts_l ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
2023-03-11 00:54:06,615 - server.py[line:210] - WARNING: https://104.20.134.21/g/2489605/952d0e6848/?hc=1&nw=always&inline_set=ts_l ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
2023-03-11 00:54:16,111 - server.py[line:210] - WARNING: https://104.20.134.21/g/2489616/0cdfd63fd4/?hc=1&nw=always&inline_set=ts_l ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
2023-03-11 00:54:23,229 - server.py[line:210] - WARNING: https://104.20.134.21/g/2474168/2d86ec8baf/?hc=1&nw=always&inline_set=ts_l ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
2023-03-11 00:54:28,262 - start.py[line:103] - ERROR: Traceback (most recent call last):
  File "view/user/login_view.py", line 50, in _AutoLogin
  File "view/user/login_widget.py", line 43, in ClickButton
  File "view/user/login_widget.py", line 50, in Login
  File "qt_owner.py", line 45, in ShowError
  File "component/label/msg_label.py", line 137, in ShowErrorEx
  File "component/label/msg_label.py", line 33, in setText
TypeError: 'PySide6.QtWidgets.QLabel.setText' called with wrong argument types:
  PySide6.QtWidgets.QLabel.setText(int)
Supported signatures:
  PySide6.QtWidgets.QLabel.setText(str)
NoneType: None
2023-03-11 00:55:26,264 - server.py[line:210] - WARNING: https://104.20.134.21/g/2474248/75c4f2eee4/?hc=1&nw=always&inline_set=ts_l ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
2023-03-11 00:55:32,718 - server.py[line:210] - WARNING: https://104.20.134.21/g/2474314/6f2cf5bfa0/?hc=1&nw=always&inline_set=ts_l ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
2023-03-11 00:55:53,474 - server.py[line:210] - WARNING: https://104.20.134.21/g/2489677/925af03a61/?hc=1&nw=always&inline_set=ts_l ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
2023-03-11 00:56:01,704 - server.py[line:210] - WARNING: https://104.20.134.21/g/2441677/f0eff1ef5b/?hc=1&nw=always&inline_set=ts_l ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
2023-03-11 00:56:11,738 - start.py[line:83] - WARNING: init scene ratio: 2.0
2023-03-11 00:56:14,584 - main_view.py[line:140] - WARNING: Waifu2x init:0, encode:0, version:1.1.6, code:0, cpuNum:0/4, gpuNum:1, gpuList:['Intel(R) UHD Graphics 617']
2023-03-11 00:56:15,235 - server.py[line:210] - WARNING: https://e-hentai.org/?inline_set=dm_l ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
2023-03-11 00:56:35,171 - server.py[line:210] - WARNING: https://exhentai.org/?inline_set=dm_l ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
2023-03-11 00:56:37,696 - start.py[line:103] - ERROR: Traceback (most recent call last):
  File "view/user/login_view.py", line 50, in _AutoLogin
  File "view/user/login_widget.py", line 43, in ClickButton
  File "view/user/login_widget.py", line 50, in Login
  File "qt_owner.py", line 45, in ShowError
  File "component/label/msg_label.py", line 137, in ShowErrorEx
  File "component/label/msg_label.py", line 33, in setText
TypeError: 'PySide6.QtWidgets.QLabel.setText' called with wrong argument types:
  PySide6.QtWidgets.QLabel.setText(int)
Supported signatures:
  PySide6.QtWidgets.QLabel.setText(str)
NoneType: None
2023-03-11 00:57:23,615 - start.py[line:103] - ERROR: Traceback (most recent call last):
  File "view/user/login_view.py", line 65, in _ClickButton
  File "view/user/login_widget.py", line 43, in ClickButton
  File "view/user/login_widget.py", line 50, in Login
  File "qt_owner.py", line 45, in ShowError
  File "component/label/msg_label.py", line 137, in ShowErrorEx
  File "component/label/msg_label.py", line 33, in setText
TypeError: 'PySide6.QtWidgets.QLabel.setText' called with wrong argument types:
  PySide6.QtWidgets.QLabel.setText(int)
Supported signatures:
  PySide6.QtWidgets.QLabel.setText(str)
NoneType: None
2023-03-11 00:57:46,346 - start.py[line:83] - WARNING: init scene ratio: 2.0
2023-03-11 00:57:49,556 - main_view.py[line:140] - WARNING: Waifu2x init:0, encode:0, version:1.1.6, code:0, cpuNum:0/4, gpuNum:1, gpuList:['Intel(R) UHD Graphics 617']
2023-03-11 00:57:50,236 - server.py[line:210] - WARNING: https://e-hentai.org/?inline_set=dm_l ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
2023-03-11 00:59:06,930 - start.py[line:83] - WARNING: init scene ratio: 2.0
2023-03-11 00:59:10,631 - main_view.py[line:140] - WARNING: Waifu2x init:0, encode:0, version:1.1.6, code:0, cpuNum:0/4, gpuNum:1, gpuList:['Intel(R) UHD Graphics 617']
2023-03-11 00:59:11,463 - server.py[line:210] - WARNING: https://e-hentai.org/?inline_set=dm_l ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
2023-03-11 00:59:15,492 - server.py[line:210] - WARNING: https://e-hentai.org/doujinshi/?inline_set=dm_l ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
2023-03-11 00:59:18,788 - server.py[line:210] - WARNING: https://e-hentai.org/doujinshi/?inline_set=dm_l ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
2023-03-11 00:59:22,933 - server.py[line:210] - WARNING: https://exhentai.org/?inline_set=dm_l ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
2023-03-11 00:59:26,913 - server.py[line:210] - WARNING: https://exhentai.org/?inline_set=dm_l ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
2023-03-11 01:00:39,916 - start.py[line:103] - ERROR: Traceback (most recent call last):
  File "view/user/login_view.py", line 50, in _AutoLogin
  File "view/user/login_widget.py", line 43, in ClickButton
  File "view/user/login_widget.py", line 50, in Login
  File "qt_owner.py", line 45, in ShowError
  File "component/label/msg_label.py", line 137, in ShowErrorEx
  File "component/label/msg_label.py", line 33, in setText
TypeError: 'PySide6.QtWidgets.QLabel.setText' called with wrong argument types:
  PySide6.QtWidgets.QLabel.setText(int)
Supported signatures:
  PySide6.QtWidgets.QLabel.setText(str)
NoneType: None
2023-03-11 01:01:26,964 - login_widget.py[line:69] - WARNING: login success, {'st': 1001, 'userId': '6897257', 'userName': 'picacg-qt'}
2023-03-11 01:01:45,327 - server.py[line:210] - WARNING: https://104.20.134.21/g/2489753/c7ff1c2aa3/?hc=1&nw=always&inline_set=ts_l ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
2023-03-11 01:04:54,384 - server.py[line:210] - WARNING: https://104.20.134.21/g/2489754/22a207eac6/?hc=1&nw=always&inline_set=ts_l ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))

**Comment by tonquer** [comment]
不确定是不是被阻断了，可以更换ip试试，待排查
