### ISSUE TITLE
登录报错证书错误

### ISSUE THREAD

**Issue by YanChiCu** [tonquer/ehentai-qt#63]
### 操作系统（如MacOS 10.15）
>win11专业版 22621.1555

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带连vpn

### 问题描述（简要描述发生的问题）
>网页进入表里站没问题，软件登录显示证书错误，个人账号和测试账号都是同样报错

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
![1](https://user-images.githubusercontent.com/131193727/232863553-c60364a0-bb5e-409f-a2eb-6ab4b0f1d42d.png)
![2](https://user-images.githubusercontent.com/131193727/232863561-c2788674-ea45-4d46-8a40-7ddd03551d52.png)
![3](https://user-images.githubusercontent.com/131193727/232863564-2d4058de-c455-48d0-80e1-915640c84989.png)

### 日志提交（问题截图或者日志，日志在logs目录）
 #>
[20230419.log](https://github.com/tonquer/ehentai-qt/files/11264798/20230419.log)

**Comment by YanChiCu** [comment]
附error
Traceback (most recent call last):
  File "view\user\login_view.py", line 50, in _AutoLogin
  File "view\user\login_widget.py", line 43, in ClickButton
  File "view\user\login_widget.py", line 50, in Login
  File "qt_owner.py", line 45, in ShowError
  File "component\label\msg_label.py", line 137, in ShowErrorEx
  File "component\label\msg_label.py", line 33, in setText
TypeError: 'PySide6.QtWidgets.QLabel.setText' called with wrong argument types:
  PySide6.QtWidgets.QLabel.setText(int)
Supported signatures:
  PySide6.QtWidgets.QLabel.setText(str)

**Comment by tonquer** [comment]
你把启用https关了，可以使用吗

**Comment by YanChiCu** [comment]
相同报错

**Comment by tonquer** [comment]
你使用的是什么代理软件，系统设置的代理地址是多少
![image](https://user-images.githubusercontent.com/22116659/232962006-12e109a6-5a85-4858-95be-861f049f4fa7.png)

https://github.com/urllib3/urllib3/issues/2075
看起来该版本库在特定代理地址情况下会出错

**Comment by YanChiCu** [comment]
https://ant.aff009.net/
换vpn试用登上了，新版本是否可解决

**Comment by tonquer** [comment]
分流代理你可以选，http代理，地址填http://127.0.0.1:1080，试试

**Comment by YanChiCu** [comment]
相同报错

<img width="243" alt="4" src="https://user-images.githubusercontent.com/131193727/233258234-145a2dd9-e664-4495-b2f4-ba0f96b45bd1.png">
还有其他可试地址吗

**Comment by tonquer** [comment]
你填完有没有点保存，麻烦再上传下日志看看

**Comment by YanChiCu** [comment]
[20230420.log](https://github.com/tonquer/ehentai-qt/files/11280139/20230420.log)

**Comment by tonquer** [comment]
下载试试，代理设置为使用系统代理
https://github.com/tonquer/ehentai-qt/actions/runs/4751108520

**Comment by YanChiCu** [comment]
同样报错 证书错误
[20230420.log](https://github.com/tonquer/ehentai-qt/files/11280610/20230420.log)

**Comment by tonquer** [comment]
麻烦你把设置里的日志等级调整为debug，再操作一下，再上传一下日志

**Comment by YanChiCu** [comment]
[20230420.log](https://github.com/tonquer/ehentai-qt/files/11282084/20230420.log)

**Comment by tonquer** [comment]
麻烦你打开帮助，打开控制台，点击下箭头，运行下以下代码看看结果，日志也上传下
![image](https://user-images.githubusercontent.com/22116659/233288921-2e87058c-dc52-49c0-80b4-649efec3c6dd.png)

```
import urllib.request; Log.Warn(urllib.request.getproxies())
```
```
import requests; Log.Warn(requests.post("https://forums.e-hentai.org/index.php?"))
```
```
import requests; Log.Warn(requests.post("https://forums.e-hentai.org/index.php?", proxies={"http":"http://127.0.0.1:1080", "https":"http://127.0.0.1:1080"}))
```

**Comment by YanChiCu** [comment]
[20230420.log](https://github.com/tonquer/ehentai-qt/files/11283497/20230420.log)

**Comment by tonquer** [comment]
你这个vpn是付费的节点会出这个错误，免费的节点可以连接吗?

**Comment by YanChiCu** [comment]
试用节点和付费节点都是相同报错

**Comment by tonquer** [comment]
试试这个，把启用Https去掉，
https://github.com/tonquer/ehentai-qt/actions/runs/4752669722

**Comment by YanChiCu** [comment]
启用仍显示证书错误，不启用则显示网络错误，确认chrome可登录网站
[20230420.log](https://github.com/tonquer/ehentai-qt/files/11284814/20230420.log)

**Comment by tonquer** [comment]
![558C215A](https://user-images.githubusercontent.com/22116659/233332729-663fb6a4-7b9d-4db4-910f-1a0601bfa5a5.png)
暂时也没查出来啥问题，你有用过bika吗，有没有出现相同的情况，https://github.com/tonquer/picacg-qt

**Comment by YanChiCu** [comment]
换了win10用了一下也是证书错误
哔咔用了一下正常运行，切分流登录均无报错
