### ISSUE TITLE
里站解析问题

### ISSUE THREAD

**Issue by csy2994** [tonquer/ehentai-qt#8]
### 操作系统（如MacOS 10.15）
>
win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
联通

### 问题描述（简要描述发生的问题）
>
连接切换里站成功 但是显示解析出错了 表站可正常使用 

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
在里站 搜索正常 图片显示正常 点进去 就显示解析出错了

### 日志提交（问题截图或者日志，日志在logs目录）
>
2022-01-16 11:32:31,178 - user_handler.py[line:210] - ERROR: 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "server\user_handler.py", line 201, in __call__
  File "server\server.py", line 141, in Send
  File "server\server.py", line 138, in __DealHeaders
  File "tools\tool.py", line 100, in GetUrlHost
AttributeError: 'NoneType' object has no attribute 'replace'
2022-01-16 11:32:45,213 - user_handler.py[line:210] - ERROR: 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "server\user_handler.py", line 201, in __call__
  File "server\server.py", line 141, in Send
  File "server\server.py", line 138, in __DealHeaders
  File "tools\tool.py", line 100, in GetUrlHost
AttributeError: 'NoneType' object has no attribute 'replace'
2022-01-16 11:32:50,000 - user_handler.py[line:210] - ERROR: 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "server\user_handler.py", line 201, in __call__
  File "server\server.py", line 141, in Send
  File "server\server.py", line 138, in __DealHeaders
  File "tools\tool.py", line 100, in GetUrlHost
AttributeError: 'NoneType' object has no attribute 'replace'
2022-01-16 11:33:04,696 - user_handler.py[line:210] - ERROR: 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "server\user_handler.py", line 201, in __call__
  File "server\server.py", line 141, in Send
  File "server\server.py", line 138, in __DealHeaders
  File "tools\tool.py", line 100, in GetUrlHost
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by tonquer** [comment]
v1.0.5发布，尝试修复这个问题，你可以下载试试
